---

server_root_dir: /webapps

virtualenv_path: "/webapps/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"

application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/celery.log"

celery_user: "{{ application_name }}"
celery_group: webapps

celery_application_name: celery
celery_scripts_dir: "{{ virtualenv_path }}/scripts/celery"
celery_template_file: "{{ celery_application_name }}_start.j2"