---

- name: Provision a {{ application_name }} web server
  hosts: webservers
  sudo: yes
  sudo_user: root
  remote_user: root
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml

  roles:
    - base
    - certbot
    - rabbitmq
    - { role: web, enable_deadsnakes_ppa: yes, virtualenv_python_version: python3.6 }
    - celery
    - nginx
